FROM freqtradeorg/freqtrade:stable_freqai

# Switch user to root if you must install something from apt
# Don't forget to switch the user back below!
# USER root

# Additional dependencies for custom strategies (FourierWaveletStrategy needs pywt)
RUN pip install --user PyWavelets==1.9.0

# Switch back to user (only if you required root above)
# USER ftuser
